title: Flavius Mihai Bendres
logo: assets/img/Profile.PNG
theme: jekyll-theme-minimal
# Navigation Bar
show_downloads: false

github: Flaviusben
linkedin: www.linkedin.com/in/flaviusben
email: benfulness24@gmail.com

# Footer Settings
footer: "© 2025 Flavius Mihai Bendres. All Rights Reserved."

